services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./best.pt:/app/best.pt  # Mounting just the model file
    environment:
      - MODEL_PATH=/app/best.pt  # Updated path to the model
